### PR TITLE
azure-devops-ci

### LINKED ISSUE #2: Put in place (azure devops) CI to run build/tests against PRs and publishing from main or tag

### PR DESCRIPTION
**Pull request by MChorfa**
This will allow azure-devops-ci 
Closes #2

### CODE REVIEW

**Comment by vdice** [comment]
Ok, the pipeline as already defined by the pre-existing azure-pipelines.yaml appears to be good: https://dev.azure.com/deislabs/porter/_build/results?buildId=6862&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=12f1170f-54f2-53f3-20dd-22fc7dff55f9

Shall we remove the copy that is on this PR?

It looks like that just leaves the `go.sum` file... but without any `go.mod` updates, I don't think it is needed, right?

**Comment by MChorfa** [comment]
> Ok, the pipeline as already defined by the pre-existing azure-pipelines.yaml appears to be good: https://dev.azure.com/deislabs/porter/_build/results?buildId=6862&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=12f1170f-54f2-53f3-20dd-22fc7dff55f9
> 
> Shall we remove the `azure-pipelines copy.yml` that is included in this PR?
> 
> It looks like that just leaves the `go.sum` file... but without any `go.mod` updates, I don't think it is needed, right?

No, it is not needed. This PR was just to make sure that the pipeline is correctly hooked up . We can ignore those 2 files and close this PR without any merging.

**Comment by vdice** [comment]
Ah, I see.  Thanks again for getting the ball rolling.  Making swift progress!

**Pull request closed without merging**
